// ================================================================
// RUNTIME ENGINE
// Converts AppConfig JSON → executable React application
// This is what makes output "directly usable" — the critical differentiator
// ================================================================

import type { AppConfig, UISchema } from "@/types";

// ── CODE GENERATOR: Produces actual React/Next.js files ──────────
export function generateRuntimeCode(config: AppConfig): Record<string, string> {
  const files: Record<string, string> = {};

  // 1. Generate types from DB schema
  files["types/generated.ts"] = generateTypes(config);

  // 2. Generate API client from API schema
  files["lib/api-client.ts"] = generateAPIClient(config);

  // 3. Generate database migrations
  files["db/migrations/001_init.sql"] = config.db.migration_sql;

  // 4. Generate auth config
  files["lib/auth.ts"] = generateAuthConfig(config);

  // 5. Generate each page
  for (const page of config.ui.pages) {
    const filePath = `app/${page.path === "/" ? "page" : page.path.replace(/^\//, "").replace(/\//g, "/")}/page.tsx`;
    files[filePath] = generatePage(page, config);
  }

  // 6. Generate layout
  files["app/layout.tsx"] = generateLayout(config);

  // 7. Generate environment template
  files[".env.example"] = generateEnvTemplate(config);

  // 8. Generate package.json
  files["package.json"] = generatePackageJson(config);

  return files;
}

function generateTypes(config: AppConfig): string {
  const types = config.db.tables.map(table => {
    const typeName = toPascalCase(table.name);
    const fields = table.columns.map(col => {
      const tsType = sqlToTsType(col.sql_type);
      return `  ${col.name}${col.nullable ? "?" : ""}: ${tsType};`;
    }).join("\n");
    return `export interface ${typeName} {\n${fields}\n}`;
  });

  return `// AUTO-GENERATED BY APPFORGE — DO NOT EDIT MANUALLY\n// Generated at: ${config.meta.generated_at}\n\n${types.join("\n\n")}`;
}

function generateAPIClient(config: AppConfig): string {
  const methods = config.api.endpoints.map(endpoint => {
    const fnName = endpointToFunctionName(endpoint.method, endpoint.path);
    const hasBody = ["POST", "PUT", "PATCH"].includes(endpoint.method);
    const params = [
      ...extractPathParams(endpoint.path).map(p => `${p}: string`),
      ...(hasBody ? ["body: Record<string, unknown>"] : []),
      ...(endpoint.query_params?.length ? ["params?: Record<string, string>"] : []),
    ].join(", ");

    const pathWithParams = endpoint.path.replace(/:([a-z_]+)/g, "${$1}");
    const queryString = endpoint.query_params?.length ? "`?${new URLSearchParams(params)}`" : '""';

    return `
export async function ${fnName}(${params}) {
  const url = \`${config.api.base_path}${pathWithParams}\`${endpoint.query_params?.length ? " + " + queryString : ""};
  const res = await fetch(url, {
    method: "${endpoint.method}",
    ${endpoint.auth_required ? 'headers: { "Authorization": \`Bearer \${getToken()}\`, "Content-Type": "application/json" },' : 'headers: { "Content-Type": "application/json" },'}
    ${hasBody ? "body: JSON.stringify(body)," : ""}
  });
  if (!res.ok) throw new Error(await res.text());
  return res.json();
}`;
  });

  return `// AUTO-GENERATED API CLIENT — AppForge Runtime\n\nfunction getToken(): string {
  return typeof window !== "undefined" ? localStorage.getItem("access_token") ?? "" : "";
}\n${methods.join("\n")}`;
}

function generatePage(page: UISchema["pages"][0], config: AppConfig): string {
  const imports = new Set(["\"use client\"", 'import { useState, useEffect } from "react"']);

  const componentCode = page.components.map(component => {
    switch (component.type) {
      case "DataTable":
        return generateDataTable(component);
      case "Form":
        return generateForm(component);
      case "StatCard":
        return generateStatCard(component);
      case "Chart":
        return generateChart(component);
      default:
        return `<div className="p-4 border rounded">${component.title ?? component.type}</div>`;
    }
  }).join("\n        ");

  return `"use client";
import { useState, useEffect } from "react";

// AUTO-GENERATED PAGE: ${page.name}
// Path: ${page.path}
// Auth required: ${page.auth_required}
// Roles: ${page.roles.join(", ") || "all"}

export default function ${toPascalCase(page.name.replace(/\s/g, ""))}Page() {
  const [data, setData] = useState<Record<string, unknown>[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-semibold">${page.name}</h1>
      ${componentCode}
    </div>
  );
}`;
}

function generateDataTable(component: UISchema["pages"][0]["components"][0]): string {
  return `
      {/* DataTable: ${component.title ?? "Data"} */}
      <div className="border rounded-lg overflow-hidden">
        <div className="p-4 border-b flex items-center justify-between">
          <h2 className="font-medium">${component.title ?? "Records"}</h2>
          ${component.actions?.map(a => `<button className="px-3 py-1 text-sm bg-blue-600 text-white rounded" onClick={() => {}}>${a.label}</button>`).join("") ?? ""}
        </div>
        <table className="w-full text-sm">
          <thead className="bg-gray-50">
            <tr>
              ${component.fields?.map(f => `<th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">${f.label}</th>`).join("") ?? "<th>ID</th><th>Name</th>"}
            </tr>
          </thead>
          <tbody className="divide-y">
            {data.map((row, i) => (
              <tr key={i} className="hover:bg-gray-50">
                ${component.fields?.map(f => `<td className="px-4 py-2">{String(row['${f.name}'] ?? '')}</td>`).join("") ?? "<td>...</td>"}
              </tr>
            ))}
          </tbody>
        </table>
        {loading && <div className="p-4 text-center text-gray-400">Loading...</div>}
        {!loading && data.length === 0 && <div className="p-4 text-center text-gray-400">No data</div>}
      </div>`;
}

function generateForm(component: UISchema["pages"][0]["components"][0]): string {
  const fields = component.fields?.map(f => {
    if (f.type === "select") {
      return `
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">${f.label}${f.required ? " *" : ""}</label>
              <select name="${f.name}" className="w-full border rounded px-3 py-2 text-sm" ${f.required ? "required" : ""}>
                ${f.options?.map(o => `<option value="${o}">${o}</option>`).join("") ?? ""}
              </select>
            </div>`;
    }
    return `
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">${f.label}${f.required ? " *" : ""}</label>
              <input type="${f.type}" name="${f.name}" placeholder="${f.label}" className="w-full border rounded px-3 py-2 text-sm" ${f.required ? "required" : ""} />
            </div>`;
  }).join("") ?? "";

  return `
      {/* Form: ${component.title ?? "Form"} */}
      <div className="border rounded-lg p-6 max-w-lg">
        <h2 className="font-medium mb-4">${component.title ?? "Form"}</h2>
        <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); }}>
          ${fields}
          <button type="submit" className="w-full bg-blue-600 text-white py-2 rounded text-sm font-medium">Submit</button>
        </form>
      </div>`;
}

function generateStatCard(component: UISchema["pages"][0]["components"][0]): string {
  return `
      <div className="bg-white border rounded-lg p-4">
        <div className="text-sm text-gray-500">${component.title ?? "Stat"}</div>
        <div className="text-3xl font-bold mt-1">—</div>
      </div>`;
}

function generateChart(component: UISchema["pages"][0]["components"][0]): string {
  return `
      <div className="border rounded-lg p-4">
        <h2 className="font-medium mb-2">${component.title ?? "Chart"}</h2>
        <div className="h-48 bg-gray-50 flex items-center justify-center text-gray-400 text-sm rounded">
          Chart placeholder — connect to {component.data_source ?? "API endpoint"}
        </div>
      </div>`;
}

function generateLayout(config: AppConfig): string {
  const navItems = config.ui.navigation.items
    .map(item => `      <a href="${item.path}" className="flex items-center gap-2 px-3 py-2 rounded text-sm hover:bg-gray-100">${item.icon ?? ""} ${item.label}</a>`)
    .join("\n");

  return `import type { Metadata } from "next";
import "./globals.css";

// AUTO-GENERATED LAYOUT — AppForge Runtime

export const metadata: Metadata = {
  title: "${config.intent.app_name}",
  description: "${config.intent.description}",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <aside className="w-56 border-r bg-white flex flex-col p-4">
            <div className="font-semibold text-lg mb-6">${config.intent.app_name}</div>
            <nav className="space-y-1">
${navItems}
            </nav>
          </aside>
          <main className="flex-1 bg-gray-50">{children}</main>
        </div>
      </body>
    </html>
  );
}`;
}

function generateAuthConfig(config: AppConfig): string {
  return `// AUTO-GENERATED AUTH CONFIG — AppForge Runtime
// Strategy: ${config.auth.strategy}
// Roles: ${config.auth.roles.map(r => r.name).join(", ")}

export const AUTH_CONFIG = ${JSON.stringify(config.auth, null, 2)};

export function hasPermission(role: string, resource: string, action: string): boolean {
  const roleConfig = AUTH_CONFIG.roles.find(r => r.name === role);
  if (!roleConfig) return false;
  const permission = roleConfig.permissions.find(p => p.resource === resource);
  if (!permission) return false;
  return permission.actions.includes(action as never);
}`;
}

function generateEnvTemplate(config: AppConfig): string {
  return `# AUTO-GENERATED BY APPFORGE
DATABASE_URL=postgresql://user:password@localhost:5432/${config.intent.app_name.toLowerCase().replace(/\s/g, "_")}
JWT_SECRET=your-secret-here
JWT_ACCESS_TTL=${config.auth.token_config.access_token_ttl}
JWT_REFRESH_TTL=${config.auth.token_config.refresh_token_ttl}
NEXT_PUBLIC_API_URL=${config.api.base_path}
${config.intent.integrations.map(i => `# ${i.toUpperCase()}_API_KEY=`).join("\n")}`;
}

function generatePackageJson(config: AppConfig): string {
  return JSON.stringify({
    name: config.intent.app_name.toLowerCase().replace(/\s/g, "-"),
    version: "0.1.0",
    private: true,
    scripts: { dev: "next dev", build: "next build", start: "next start" },
    dependencies: {
      next: "14.2.5",
      react: "^18",
      "react-dom": "^18",
      "tailwindcss": "^3.4.1",
    },
  }, null, 2);
}

// ── EXECUTION VALIDATOR: Check if generated code is syntactically valid ──
export function validateGeneratedCode(files: Record<string, string>): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  for (const [path, content] of Object.entries(files)) {
    if (path.endsWith(".ts") || path.endsWith(".tsx")) {
      // Basic syntax checks
      const openBraces = (content.match(/\{/g) ?? []).length;
      const closeBraces = (content.match(/\}/g) ?? []).length;
      if (Math.abs(openBraces - closeBraces) > 2) {
        errors.push(`${path}: Unbalanced braces (${openBraces} open, ${closeBraces} close)`);
      }

      if (content.includes("undefined.") || content.includes("null.")) {
        errors.push(`${path}: Potential null reference`);
      }
    }

    if (path.endsWith(".sql")) {
      if (!content.includes("CREATE TABLE") && !content.includes("create table")) {
        errors.push(`${path}: SQL migration missing CREATE TABLE statements`);
      }
    }
  }

  return { valid: errors.length === 0, errors };
}

// ── HELPERS ──────────────────────────────────────────────────────
function toPascalCase(str: string): string {
  return str.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase());
}

function sqlToTsType(sqlType: string): string {
  const lower = sqlType.toLowerCase();
  if (lower.includes("int") || lower.includes("float") || lower.includes("decimal") || lower.includes("numeric")) return "number";
  if (lower.includes("bool")) return "boolean";
  if (lower.includes("timestamp") || lower.includes("date")) return "string";
  if (lower.includes("json")) return "Record<string, unknown>";
  if (lower.includes("uuid")) return "string";
  return "string";
}

function endpointToFunctionName(method: string, path: string): string {
  const parts = path.replace(/\//g, "_").replace(/:/g, "").replace(/-/g, "_").split("_").filter(Boolean);
  const action = method.toLowerCase();
  return `${action}${parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join("")}`;
}

function extractPathParams(path: string): string[] {
  return [...path.matchAll(/:([a-z_]+)/g)].map(m => m[1]);
}
